### PR TITLE
Fix blinking buttons while bot is writing

### PR DESCRIPTION
**Pull request by pedrokohler**
Currently the buttons start blinking, appearing and disappearing hundreds of times while the bot is typing.

This PR fixes it.

### CODE REVIEW

**Comment by pedrokohler** [comment]
@liady I've made these changes locally and tested it successfully. Hopefully we can merge this to the main repo.

Regards.

**Review by liady — APPROVED** [review]

**Review by liady — APPROVED** [review]

**Comment by rjRostana** [comment]
Sorry - am a bit of an amateur on this.

Can you past a link to where I go to get an update of the fix?

**Comment by lakylekidd** [comment]
I tested this one and when the bot is not typing it doesn't show the buttons any more. I don't think that fixes it.

**Comment by bobnimon** [comment]
As you are looking at this, know that the buttons blink when the bot is not typing as well (without this fix).

**Comment by Daniel-Waiger** [comment]
I pulled it from github, now I don't have the buttons at all

**Comment by dominic11152000** [comment]
> I pulled it from github, now I don't have the buttons at all

I am currently facing the same issue :(

**Pull request merged**
