### PR TITLE
Fix: Buttons keep flashing & "Share Link" Button Not Working

### PR DESCRIPTION
**Pull request by aspiriine**
a quick fix for the buttons flashing and showing up when chatgpt hasn't fully loaded.
Tested locally and it works. Someone also confirmed it working.
This is my first PR, if I messed up please let me know

### CODE REVIEW

**Comment by jeemitsha** [comment]
share link is not working bro

**Comment by cjauvin** [comment]
I confirm: this fixes the flashing issue, but the sharing button does not seem to work.

**Comment by aspiriine** [comment]
It should work now.

**Comment by cjauvin** [comment]
yes it does, thanks!

**Comment by andresn** [comment]
The Chrome build works (thank you!). Is anyone else having issues with the buttons not showing up in FFox 112.0?

**Comment by aspiriine** [comment]
> The Chrome build works (thank you!). Is anyone else having issues with the buttons not showing up in FFox 112.0?

Nope. They do show up. Although I could only make the extension work on the FFox dev edition as it requires the addon to be signed.

**Pull request closed without merging**
