### PR TITLE
Fix: Uncaught TypeError: Cannot read properties of null (reading 'style')

### PR DESCRIPTION
**Pull request by rmcc3**
The error is caused by changes in ChatGPT UI with the spacer. This request fixes that.

### CODE REVIEW

**Comment by DhruvDh** [comment]
This fixes generation of PDFs and PNGs for me, but Share Link is still broken -

```
content_script.js:255 

       Uncaught (in promise) TypeError: Cannot read properties of null (reading 'sheet')
          at getData (content_script.js:255:72)
          at sendRequest (content_script.js:231:16)
          at exportHtml.onclick (content_script.js:110:5)
          getData @ content_script.js:255
          sendRequest @ content_script.js:231
          exportHtml.onclick @ content_script.js:110
```

**Comment by rmcc3** [comment]
> DhruvDh

Fixed. Seems they changed the UI framework.

**Comment by rmcc3** [comment]
> This fixes generation of PDFs and PNGs for me, but Share Link is still broken -
> 
> ```
> content_script.js:255 
> 
>        Uncaught (in promise) TypeError: Cannot read properties of null (reading 'sheet')
>           at getData (content_script.js:255:72)
>           at sendRequest (content_script.js:231:16)
>           at exportHtml.onclick (content_script.js:110:5)
>           getData @ content_script.js:255
>           sendRequest @ content_script.js:231
>           exportHtml.onclick @ content_script.js:110
> ```

Fixed. Seems they updated the UI framework.

**Comment by saurabh20** [comment]
Here are a couple of errors in the chrome extension 
chatgpt-exten-error
chatgpt-ext-errors
Please fix it as its not working on Chrome [macOS]

**Comment by rmcc3** [comment]
> Here are a couple of errors in the chrome extension chatgpt-exten-error chatgpt-ext-errors Please fix it as its not working on Chrome [macOS]

It is working. Are you sure you downloaded this pull and updated the extension? Try removing the current extension and downloading it directly from my repo.

[rmcc3/ChatGPT-pdf](https://github.com/rmcc3/ChatGPT-pdf)

**Comment by tovstyi** [comment]
image

**Comment by gzur** [comment]
Fixes #45

**Comment by smithnigelw** [comment]
I've tried this extension (v1.3.6) today on both Microsoft Edge and Google Chrome, both v110. But 'Inspect views' is saying 'No active views'. Please can you offer any advice on how to debug this situation.

**Pull request closed without merging**
